#!/usr/bin/env python
"""Add photo to storage."""

from itertools import imap

from photostore.image import Image
from photostore.storage import Storage


def importphotos(files, storepath):
    """Process import photo request."""

    with Storage(storepath) as store:
        for img in imap(Image, files):
            print img.old_path, '...',
            store.insert(img)


if __name__ == '__main__':

    from sys import argv
    from os import path, walk, mkdir
    from itertools import chain

    storepath = path.expandvars("$HOME/.photostore")

    # Make sure store dir exists
    if not path.isdir(storepath):
        mkdir(storepath)

    # Build file list
    files = []
    for arg in argv[1:]:
        if path.isdir(arg):
            for root, dirs, dir_files in walk(arg):
                for file in dir_files:
                    files.append(path.join(root, file))
        elif path.isfile(arg):
            files.append(arg)

    # Import files into store
    try:
        importphotos(files, storepath)
    except KeyboardInterrupt:
        print "Import aborted by user"
        exit()
    
