#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#------------------------------------------------------------------------#
# PhotoStore - Photo Collection Storage
# Copyright (C) 2010 Adam Wagner <awagner83@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------#
"""Add photo to storage."""

import logging
from sys import argv
from os import path, walk, mkdir
from itertools import chain

from photostore.image import Image
from photostore.storage import Storage
from photostore.path import iterfiles


def importphotos(files, storepath):
    """Process import photo request."""

    with Storage(storepath) as store:
        for img in map(Image, files):
            logging.info("Saving %s..." % img.old_path)
            store.insert(img)


if __name__ == '__main__':

    logging.basicConfig(level=logging.INFO)
    storepath = path.expandvars("$HOME/.photostore")

    # Make sure store dir exists
    if not path.isdir(storepath):
        mkdir(storepath)

    # Import files into store
    try:
        importphotos(iterfiles(argv[1:]), storepath)
    except KeyboardInterrupt:
        logging.info("Import aborted by user.")
        exit()
    
