#!/usr/bin/env python3
#------------------------------------------------------------------------#
# PhotoStore - Photo Collection Storage
# Copyright (C) 2010 Adam Wagner <awagner83@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------#
"""Add photo to storage."""


from photostore.image import Image
from photostore.storage import Storage
from photostore.path import iterfiles


def importphotos(files, storepath):
    """Process import photo request."""

    with Storage(storepath) as store:
        for img in map(Image, files):
            print(img.old_path, '...', end=' ')
            store.insert(img)


if __name__ == '__main__':

    from sys import argv
    from os import path, walk, mkdir
    from itertools import chain

    storepath = path.expandvars("$HOME/.photostore")

    # Make sure store dir exists
    if not path.isdir(storepath):
        mkdir(storepath)

    # Import files into store
    try:
        importphotos(iterfiles(argv[1:]), storepath)
    except KeyboardInterrupt:
        print("Import aborted by user")
        exit()
    
